### ISSUE TITLE
Request an explanation!

### ISSUE THREAD

**Issue by wangweifei-504** [volkserg/CSE-CIC-IDS2018-learning_models#1]
Can you explain your work, dear friend? Or can you share your paper?

**Comment by volkserg** [comment]
> Can you explain your work, dear friend? Or can you share your paper?

Hello! Here are links to papers: 

[Volkov, S. S., & Kurochkin, I. I. (2020). Network attacks classification using Long Short-term memory based neural networks in Software-Defined Networks. Procedia Computer Science, 178, 394-403.](https://www.sciencedirect.com/science/article/pii/S1877050920324200/pdf?md5=130506f04776b41ca66a187ac50f1eae&pid=1-s2.0-S1877050920324200-main.pdf)

[Kurochkin, I. I., & Volkov, S. S. (2020, September). Using GRU based deep neural network for intrusion detection in software-defined networks. In IOP Conference Series: Materials Science and Engineering (Vol. 927, No. 1, p. 012035). IOP Publishing.](https://iopscience.iop.org/article/10.1088/1757-899X/927/1/012035/pdf)

**Comment by wangweifei-504** [comment]
Already received, thank you for your help!
